spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/perfume
    username: postgres
    password: root

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    username: eeleu44@gmail.com
    password: dyeulhjokrgbzjin
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 615660542975-d8l8ssra58emh139orl2bl50hm6utsg0.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId: c58275a0f2d5d563db8f
            clientSecret: 47581aef6e3c9796e146e3a870d6b678b6853aad
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - read:user
              - user:email

mail:
  debug: false


recaptcha:
  secret: 6LcLLVQgAAAAAOjBcLcxlEpLEysLsjBMzIGxHEU6
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s

hostname: localhost:4200

jwt:
  header: Authorization
  secret: dejavu
  expiration: 3600000