spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/perfume
    username: postgres
    password: root

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    username: #data
    password: #data
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: #data
            client-secret: #data
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId: #data
            clientSecret: #data
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - read:user
              - user:email

mail:
  debug: false


recaptcha:
  secret: #data
  url: https://www.google.com/recaptcha/api/siteverify?secret=%s&response=%s

hostname: localhost:4200

jwt:
  header: Authorization
  secret: dejavu
  expiration: 3600000
